// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DISCOVERY_SERVICE`, `IROH_ENDPOINT`, `IROH_ROUTER`, `PENDING_REQUESTS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`, `initialize`

String generateRandomShortId() =>
    RustLib.instance.api.crateApiGenerateRandomShortId();

Stream<FrbTransferEvent> initBackend(
        {required String shortId, required String outputDir}) =>
    RustLib.instance.api
        .crateApiInitBackend(shortId: shortId, outputDir: outputDir);

void setOutputDir({required String dir}) =>
    RustLib.instance.api.crateApiSetOutputDir(dir: dir);

Future<void> respondToTransfer(
        {required String requestId, required bool accepted}) =>
    RustLib.instance.api
        .crateApiRespondToTransfer(requestId: requestId, accepted: accepted);

/// Pause an active transfer (both TCP and QUIC paths register their flags).
Future<void> pauseTransfer({required String requestId}) =>
    RustLib.instance.api.crateApiPauseTransfer(requestId: requestId);

/// Resume a paused transfer.
Future<void> resumeTransfer({required String requestId}) =>
    RustLib.instance.api.crateApiResumeTransfer(requestId: requestId);

/// Cancel an active transfer.
Future<void> cancelTransfer({required String requestId}) =>
    RustLib.instance.api.crateApiCancelTransfer(requestId: requestId);

Future<bool> checkPeerOnline({required String shortId}) =>
    RustLib.instance.api.crateApiCheckPeerOnline(shortId: shortId);

Stream<FrbTransferEvent> sendFile(
        {required String requestId,
        required String targetShortId,
        required String filePath,
        required String senderName}) =>
    RustLib.instance.api.crateApiSendFile(
        requestId: requestId,
        targetShortId: targetShortId,
        filePath: filePath,
        senderName: senderName);

@freezed
sealed class FrbTransferEvent with _$FrbTransferEvent {
  const FrbTransferEvent._();

  const factory FrbTransferEvent.sendStatus({
    required String requestId,
    required String status,
  }) = FrbTransferEvent_SendStatus;
  const factory FrbTransferEvent.rejected({
    required String requestId,
  }) = FrbTransferEvent_Rejected;
  const factory FrbTransferEvent.error({
    required String requestId,
    required String error,
  }) = FrbTransferEvent_Error;
  const factory FrbTransferEvent.incoming({
    required String requestId,
    required String senderName,
    required String senderNodeId,
    required String fileName,
    required BigInt fileSize,
  }) = FrbTransferEvent_Incoming;
  const factory FrbTransferEvent.progress({
    required String requestId,
    required BigInt bytesTransferred,
    required BigInt total,
    required double speedBytesPerSec,
  }) = FrbTransferEvent_Progress;
  const factory FrbTransferEvent.complete({
    required String requestId,
    required String filePath,
    required String blake3Hash,
    required double elapsedSecs,
  }) = FrbTransferEvent_Complete;
  const factory FrbTransferEvent.cancelled({
    required String requestId,
  }) = FrbTransferEvent_Cancelled;
}
