// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1219562821;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_p2ptransfer',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCancelTransfer({required String requestId});

  Future<bool> crateApiCheckPeerOnline({required String shortId});

  String crateApiGenerateRandomShortId();

  Stream<FrbTransferEvent> crateApiInitBackend(
      {required String shortId, required String outputDir});

  Future<void> crateApiPauseTransfer({required String requestId});

  Future<void> crateApiRespondToTransfer(
      {required String requestId, required bool accepted});

  Future<void> crateApiResumeTransfer({required String requestId});

  Stream<FrbTransferEvent> crateApiSendFile(
      {required String requestId,
      required String targetShortId,
      required String filePath,
      required String senderName});

  void crateApiSetOutputDir({required String dir});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCancelTransfer({required String requestId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(requestId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCancelTransferConstMeta,
      argValues: [requestId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCancelTransferConstMeta => const TaskConstMeta(
        debugName: "cancel_transfer",
        argNames: ["requestId"],
      );

  @override
  Future<bool> crateApiCheckPeerOnline({required String shortId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(shortId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCheckPeerOnlineConstMeta,
      argValues: [shortId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCheckPeerOnlineConstMeta => const TaskConstMeta(
        debugName: "check_peer_online",
        argNames: ["shortId"],
      );

  @override
  String crateApiGenerateRandomShortId() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateRandomShortIdConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateRandomShortIdConstMeta =>
      const TaskConstMeta(
        debugName: "generate_random_short_id",
        argNames: [],
      );

  @override
  Stream<FrbTransferEvent> crateApiInitBackend(
      {required String shortId, required String outputDir}) {
    final eventSink = RustStreamSink<FrbTransferEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(shortId, serializer);
        sse_encode_String(outputDir, serializer);
        sse_encode_StreamSink_frb_transfer_event_Sse(eventSink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitBackendConstMeta,
      argValues: [shortId, outputDir, eventSink],
      apiImpl: this,
    )));
    return eventSink.stream;
  }

  TaskConstMeta get kCrateApiInitBackendConstMeta => const TaskConstMeta(
        debugName: "init_backend",
        argNames: ["shortId", "outputDir", "eventSink"],
      );

  @override
  Future<void> crateApiPauseTransfer({required String requestId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(requestId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPauseTransferConstMeta,
      argValues: [requestId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPauseTransferConstMeta => const TaskConstMeta(
        debugName: "pause_transfer",
        argNames: ["requestId"],
      );

  @override
  Future<void> crateApiRespondToTransfer(
      {required String requestId, required bool accepted}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(requestId, serializer);
        sse_encode_bool(accepted, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRespondToTransferConstMeta,
      argValues: [requestId, accepted],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRespondToTransferConstMeta => const TaskConstMeta(
        debugName: "respond_to_transfer",
        argNames: ["requestId", "accepted"],
      );

  @override
  Future<void> crateApiResumeTransfer({required String requestId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(requestId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiResumeTransferConstMeta,
      argValues: [requestId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResumeTransferConstMeta => const TaskConstMeta(
        debugName: "resume_transfer",
        argNames: ["requestId"],
      );

  @override
  Stream<FrbTransferEvent> crateApiSendFile(
      {required String requestId,
      required String targetShortId,
      required String filePath,
      required String senderName}) {
    final eventSink = RustStreamSink<FrbTransferEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(requestId, serializer);
        sse_encode_String(targetShortId, serializer);
        sse_encode_String(filePath, serializer);
        sse_encode_String(senderName, serializer);
        sse_encode_StreamSink_frb_transfer_event_Sse(eventSink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSendFileConstMeta,
      argValues: [requestId, targetShortId, filePath, senderName, eventSink],
      apiImpl: this,
    )));
    return eventSink.stream;
  }

  TaskConstMeta get kCrateApiSendFileConstMeta => const TaskConstMeta(
        debugName: "send_file",
        argNames: [
          "requestId",
          "targetShortId",
          "filePath",
          "senderName",
          "eventSink"
        ],
      );

  @override
  void crateApiSetOutputDir({required String dir}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dir, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSetOutputDirConstMeta,
      argValues: [dir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetOutputDirConstMeta => const TaskConstMeta(
        debugName: "set_output_dir",
        argNames: ["dir"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<FrbTransferEvent> dco_decode_StreamSink_frb_transfer_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrbTransferEvent dco_decode_frb_transfer_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return FrbTransferEvent_SendStatus(
          requestId: dco_decode_String(raw[1]),
          status: dco_decode_String(raw[2]),
        );
      case 1:
        return FrbTransferEvent_Rejected(
          requestId: dco_decode_String(raw[1]),
        );
      case 2:
        return FrbTransferEvent_Error(
          requestId: dco_decode_String(raw[1]),
          error: dco_decode_String(raw[2]),
        );
      case 3:
        return FrbTransferEvent_Incoming(
          requestId: dco_decode_String(raw[1]),
          senderName: dco_decode_String(raw[2]),
          senderNodeId: dco_decode_String(raw[3]),
          fileName: dco_decode_String(raw[4]),
          fileSize: dco_decode_u_64(raw[5]),
        );
      case 4:
        return FrbTransferEvent_Progress(
          requestId: dco_decode_String(raw[1]),
          bytesTransferred: dco_decode_u_64(raw[2]),
          total: dco_decode_u_64(raw[3]),
          speedBytesPerSec: dco_decode_f_64(raw[4]),
        );
      case 5:
        return FrbTransferEvent_Complete(
          requestId: dco_decode_String(raw[1]),
          filePath: dco_decode_String(raw[2]),
          blake3Hash: dco_decode_String(raw[3]),
          elapsedSecs: dco_decode_f_64(raw[4]),
        );
      case 6:
        return FrbTransferEvent_Cancelled(
          requestId: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<FrbTransferEvent> sse_decode_StreamSink_frb_transfer_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FrbTransferEvent sse_decode_frb_transfer_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_requestId = sse_decode_String(deserializer);
        var var_status = sse_decode_String(deserializer);
        return FrbTransferEvent_SendStatus(
            requestId: var_requestId, status: var_status);
      case 1:
        var var_requestId = sse_decode_String(deserializer);
        return FrbTransferEvent_Rejected(requestId: var_requestId);
      case 2:
        var var_requestId = sse_decode_String(deserializer);
        var var_error = sse_decode_String(deserializer);
        return FrbTransferEvent_Error(
            requestId: var_requestId, error: var_error);
      case 3:
        var var_requestId = sse_decode_String(deserializer);
        var var_senderName = sse_decode_String(deserializer);
        var var_senderNodeId = sse_decode_String(deserializer);
        var var_fileName = sse_decode_String(deserializer);
        var var_fileSize = sse_decode_u_64(deserializer);
        return FrbTransferEvent_Incoming(
            requestId: var_requestId,
            senderName: var_senderName,
            senderNodeId: var_senderNodeId,
            fileName: var_fileName,
            fileSize: var_fileSize);
      case 4:
        var var_requestId = sse_decode_String(deserializer);
        var var_bytesTransferred = sse_decode_u_64(deserializer);
        var var_total = sse_decode_u_64(deserializer);
        var var_speedBytesPerSec = sse_decode_f_64(deserializer);
        return FrbTransferEvent_Progress(
            requestId: var_requestId,
            bytesTransferred: var_bytesTransferred,
            total: var_total,
            speedBytesPerSec: var_speedBytesPerSec);
      case 5:
        var var_requestId = sse_decode_String(deserializer);
        var var_filePath = sse_decode_String(deserializer);
        var var_blake3Hash = sse_decode_String(deserializer);
        var var_elapsedSecs = sse_decode_f_64(deserializer);
        return FrbTransferEvent_Complete(
            requestId: var_requestId,
            filePath: var_filePath,
            blake3Hash: var_blake3Hash,
            elapsedSecs: var_elapsedSecs);
      case 6:
        var var_requestId = sse_decode_String(deserializer);
        return FrbTransferEvent_Cancelled(requestId: var_requestId);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_frb_transfer_event_Sse(
      RustStreamSink<FrbTransferEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_frb_transfer_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_frb_transfer_event(
      FrbTransferEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case FrbTransferEvent_SendStatus(
          requestId: final requestId,
          status: final status
        ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(requestId, serializer);
        sse_encode_String(status, serializer);
      case FrbTransferEvent_Rejected(requestId: final requestId):
        sse_encode_i_32(1, serializer);
        sse_encode_String(requestId, serializer);
      case FrbTransferEvent_Error(
          requestId: final requestId,
          error: final error
        ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(requestId, serializer);
        sse_encode_String(error, serializer);
      case FrbTransferEvent_Incoming(
          requestId: final requestId,
          senderName: final senderName,
          senderNodeId: final senderNodeId,
          fileName: final fileName,
          fileSize: final fileSize
        ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(requestId, serializer);
        sse_encode_String(senderName, serializer);
        sse_encode_String(senderNodeId, serializer);
        sse_encode_String(fileName, serializer);
        sse_encode_u_64(fileSize, serializer);
      case FrbTransferEvent_Progress(
          requestId: final requestId,
          bytesTransferred: final bytesTransferred,
          total: final total,
          speedBytesPerSec: final speedBytesPerSec
        ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(requestId, serializer);
        sse_encode_u_64(bytesTransferred, serializer);
        sse_encode_u_64(total, serializer);
        sse_encode_f_64(speedBytesPerSec, serializer);
      case FrbTransferEvent_Complete(
          requestId: final requestId,
          filePath: final filePath,
          blake3Hash: final blake3Hash,
          elapsedSecs: final elapsedSecs
        ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(requestId, serializer);
        sse_encode_String(filePath, serializer);
        sse_encode_String(blake3Hash, serializer);
        sse_encode_f_64(elapsedSecs, serializer);
      case FrbTransferEvent_Cancelled(requestId: final requestId):
        sse_encode_i_32(6, serializer);
        sse_encode_String(requestId, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
