version: "3.9"

services:
  registry:
    build:
      context: ..
      dockerfile: registry-server/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  relay:
    build:
      context: ..
      dockerfile: registry-server/Dockerfile.relay
    ports:
      - "9878:9878"
    restart: unless-stopped
